version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"
    reviewers:
      - "project-maintainers"
    ignore:
      - dependency-name: "expo"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-native"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "web"
      - "automerge"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"